<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Adminhtml\System\Config\Validatevat $block */
?>
<script>
require(['prototype'], function(){
//<![CDATA[
    function configureGST() {
        var validationMessage = $('validation_result');

        params = {
            region: $('<?= $block->escapeJs($block->getMerchantRegionField()) ?>').value
        };

        new Ajax.Request('<?= $block->escapeJs($block->escapeUrl($block->getAjaxUrl())) ?>', {
            parameters: params,
            onSuccess: function(response) {
                var result = '<?= $block->escapeJs($block->escapeHtml(__('Error during GST configuration.'))) ?>';
                try {
                    if (response.responseText.isJSON()) {
                        response = response.responseText.evalJSON();
                        result = response.message;
                    }
                    if (response.valid == 1) {
                        validationMessage.removeClassName('hidden').addClassName('success')
                    } else {
                        validationMessage.removeClassName('hidden').addClassName('error')
                    }
                } catch (e) {
                    validationMessage.removeClassName('hidden').addClassName('error')
                }
                validationMessage.update(result);
            }
        });
    }
    window.configureGST = configureGST;
//]]>

});
</script>
<div class="actions actions-configure-gst">
    <div id="validation_result" class="message-validation hidden"></div>
    <button onclick="javascript:configureGST(); return false;" class="action-configure-gst" type="button" id="<?= $block->escapeHtmlAttr($block->getHtmlId()) ?>">
        <span><?= $block->escapeHtml($block->getButtonLabel()) ?></span>
    </button>
</div>
